### ISSUE TITLE
JanusGraph #719

### ISSUE THREAD

**Issue by roliygu** [OTAKU-Wang/MahoutDemo#1]
请问这个问题你解决了吗

**Comment by roliygu** [comment]
https://github.com/JanusGraph/janusgraph/issues/719

**Comment by chaipugao** [comment]
问题解决了吗？遇到了同样的问题，求帮助

**Comment by OTAKU-Wang** [comment]
问题解决了。主要是一些配置和jar兼容性的问题。[参考文档](https://www.jianshu.com/p/09d0ae1bc621)

**Comment by chaipugao** [comment]
@OTAKU-Wang 麻烦问下 httpcore 和 httpclient用的是哪个版本呢？

**Comment by OTAKU-Wang** [comment]
这个要看你用的大数据组件里面用的什么版本。

2018-05-15 15:20 GMT+08:00 chaipugao <notifications@github.com>:

**Comment by chaipugao** [comment]
spark用的是1.6.1，看起来是spark的httpcore 和 janus的httpcore冲突了。spark升高到2.3版本后，janus提交任务有问题，感觉janus默认还是用的1.6的spark_submit提交的任务

**Comment by OTAKU-Wang** [comment]
spark2.x版本现在的janusgraph应该是不支持的。。。最好用他官方的版本。

2018-05-16 10:23 GMT+08:00 chaipugao <notifications@github.com>:

**Comment by roliygu** [comment]
不如建个群讨论。。JanusGraph用的人还少，问题不集中，微信号发邮件给我，roliygu@gmail.com
